teve-guide/Controllers/tv_showsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.ServiceModel.Channels;
using System.Web.Mvc;
using teve_guide.Models.db;
using System;
using System.Web;
using teve_guide.Models;
using teve_guide.Security;

namespace teve_guide.Controllers
{
    public class tv_showsController : Controller
    {
    private TeveGuideEntities db = new TeveGuideEntities();

   
    // GET: tv_shows
    public ActionResult Index()
        {
            return View(db.tv_shows.ToList());
        }

        //Get current Tv-table
        public ActionResult CurrentTvTable(string channel)
        {
            var currentChannel = from c in db.tv_shows
                                 where c.Channel.Contains(channel)
                                 select c;

            return View(currentChannel.ToList());
        }

        public ActionResult TomorrowTvTable(string channel)
        {
            var currentChannel = from c in db.tv_shows
                                 orderby c.Starttime
                                 where c.Channel.Contains(channel)
                                 select c;

            return View(currentChannel);
           
        }

        public ActionResult InTwoDaysTvTable(string channel)
        {
            var currentChannel = from c in db.tv_shows
                                 where c.Channel.Contains(channel)
                                 select c;

            return View(currentChannel.ToList());
        }

        public ActionResult InThreeDaysTvTable(string channel)
        {
            var currentChannel = from c in db.tv_shows
                                 where c.Channel.Contains(channel)
                                 select c;

            return View(currentChannel.ToList());
        }

        public ActionResult InFourDaysTvTable(string channel)
        {
            var currentChannel = from c in db.tv_shows
                                 where c.Channel.Contains(channel)
                                 select c;

            return View(currentChannel.ToList());
        }

        public ActionResult InFiveDaysTvTable(string channel)
        {
            var currentChannel = from c in db.tv_shows
                                 where c.Channel.Contains(channel)
                                 select c;

            return View(currentChannel.ToList());
        }

        public ActionResult InSixDaysTvTable(string channel)
        {
            var currentChannel = from c in db.tv_shows
                                 where c.Channel.Contains(channel)
                                 select c;

            return View(currentChannel.ToList());
        }

        // GET: tv_shows/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tv_shows tv_shows = db.tv_shows.Find(id);
            if (tv_shows == null)
            {
                return HttpNotFound();
            }
            return View(tv_shows);
        }


        [Authorize]

        public ActionResult MyPage(string channel)
        {
            ViewBag.Channel = (from c in db.tv_shows select c.Channel).Distinct();

            var model = from c in db.tv_shows
                        orderby c.Channel
                        where c.Channel == channel || channel == null || channel == ""
                        select c;
            return View(model);
        
        }

        public ActionResult MyPageView(FormCollection collection)
        {
            try
            {
                ViewBag.TvChannels = collection["channel"];
            }
            catch 
            {
                ViewBag.Message = "Det blev en catch...";
            }
            return View();
        }

        [HttpPost]
        public ActionResult ShowTvshow(TvShow model)
        {
            return View();
        }

        // GET: tv_shows/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tv_shows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Starttime,Endtime,Substance,Category,Channel")] tv_shows tv_shows)
        {
            if (ModelState.IsValid)
            {

                db.tv_shows.Add(tv_shows);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tv_shows);
        }

        // GET: tv_shows/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tv_shows tv_shows = db.tv_shows.Find(id);
            if (tv_shows == null)
            {
                return HttpNotFound();
            }
            return View(tv_shows);
        }

        // POST: tv_shows/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Starttime,Endtime,Substance,Category,Channel")] tv_shows tv_shows)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tv_shows).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tv_shows);
        }

        // GET: tv_shows/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tv_shows tv_shows = db.tv_shows.Find(id);
            if (tv_shows == null)
            {
                return HttpNotFound();
            }
            return View(tv_shows);
        }

        // POST: tv_shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tv_shows tv_shows = db.tv_shows.Find(id);
            db.tv_shows.Remove(tv_shows);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [AuthorizeRoles("Admin")]

        public ActionResult AdminPage()
        {
            ViewBag.Message = "Endast administratörer.";
            //return View();
            return View(db.tv_shows.ToList());

        }

        [HttpPost]
        public ActionResult SetPuffId(int id)
        {
            ViewBag.Puff1 = id;
            return RedirectToAction("Index");
        }

    }
}

teve-guide/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("På TV", "Index", "tv_shows", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Idag", "Today", "Home")</li>
                    <li>@Html.ActionLink("Imorgon", "Tomorrow", "Home")</li>
                    <li>@Html.ActionLink("Om två dagar", "TwoDaysFromNow", "Home")</li>
                    <li>@Html.ActionLink("Om tre dagar", "ThreeDaysFromNow", "Home")</li>
                    <li>@Html.ActionLink("Om fyra dagar", "FourDaysFromNow", "Home")</li>
                    <li>@Html.ActionLink("Om fem dagar", "FiveDaysFromNow", "Home")</li>
                    <li>@Html.ActionLink("Om sex dagar", "SixDaysFromNow", "Home")</li>
                    <li>@Html.ActionLink("Min sida", "MyPage", "tv_shows")</li>
                    <li>@Html.ActionLink("Administrera", "AdminPage", "tv_shows")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Logga ut", "SignOut", "Account")</li>

                    }
                </ul>
               
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

teve-guide/Views/Shared/_Puff1.cshtml
@model IEnumerable<teve_guide.Models.db.tv_shows>

@{
    ViewBag.Title = "På teve just nu";
    var puff1 = 5032;
    //var puff1 = @ViewBag.Puff1;



}

<br />

<table class="table">
    <tr>
        <td>
            <!--Puff-->

            @foreach (var p in Model)
            {

                if (p.Id==puff1)
                {
                <strong>@p.Title</strong> <br />
                @p.Substance <br />
                @p.Channel <br />
                @p.Starttime <br />

                @Html.ActionLink("Mer info", "Details", new { id = p.Id }) <br />
                }
            }


        </td>

    </tr>
</table>

teve-guide/Views/Shared/_Puff2.cshtml
@model IEnumerable<teve_guide.Models.db.tv_shows>

@{
    ViewBag.Title = "På teve just nu";
    var puff2 = 5003;
}


<br />

<table class="table">
    <tr>
        <td>
            <!--Puff-->

            @foreach (var p in Model)
            {
                if(p.Id==puff2)
                { 
                <strong>@p.Title</strong> <br />
                @p.Substance <br />
                @p.Channel <br />
                @p.Starttime <br />

                @Html.ActionLink("Mer info", "Details", new { id = p.Id }) <br />
                }
            }



        </td>
    </tr>
</table>

teve-guide/Views/Shared/_Puff3.cshtml
@model IEnumerable<teve_guide.Models.db.tv_shows>

@{
    ViewBag.Title = "På teve just nu";
    var puff3 = 5010;
}


<br />

<table class="table">
    <tr>
        <td>
            <!--Puff-->

            @foreach (var p in Model)
            {
                if(p.Id==puff3)
                { 
                <strong>@p.Title</strong> <br />
                @p.Substance <br />
                @p.Channel <br />
                @p.Starttime <br />

                @Html.ActionLink("Mer info", "Details", new { id = p.Id }) <br />
                }
            }



        </td>
    </tr>
</table>

teve-guide/Views/Shared/_Puffar.cshtml
@model IEnumerable<teve_guide.Models.db.tv_shows>

@{
    ViewBag.Title = "På teve just nu";
}


<br />

<table class="table">
    <tr>
        <td>
            <!--Puff-->
            @*@foreach (var item in Model)


                   {
                       if (item.Id == 1004)
                       {
                        <strong>@Html.DisplayFor(modelItem => item.Title)</strong> <br />
                        @Html.DisplayFor(modelItem => item.Substance) <br />
                        @Html.DisplayFor(modelItem => item.Channel) <br />
                        @Html.DisplayFor(modelItem => item.Starttime) <br />
                        @Html.ActionLink("Mer info", "Details", new { id = item.Id })
                    }
                }*@

            @foreach (var p in Model)
            {
                if(p.Id==25)
                { 
                <strong>@p.Title</strong> <br />
                @p.Substance <br />
                @p.Channel <br />
                @p.Starttime <br />

                @Html.ActionLink("Mer info", "Details", new { id = p.Id }) <br />
                }
            }



        </td>



        <td>

            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Mer info", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>*@
    </tr>
</table>